# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SpringGraph
version:      0.01
version_from: lib/SpringGraph.pm
installdirs:  site
requires:
    GD:                            1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
